import type { Lesson } from '../types'

const loadBalancer: Lesson = {
  slug: 'load-balancer',
  title: 'Round-Robin Load Balancing',
  summary: 'Spread traffic across servers — and route around the ones that die.',
  group: 'building-blocks',
  topic: 'Load Balancer',
  tier: 'free',
  minutes: 7,
  concept: 'Concept',
  tags: [
    { label: 'Availability', value: 'High' },
    { label: 'Pattern', value: 'Round-robin' },
    { label: 'Scalability', value: 'Horizontal' },
  ],
  notes: [
    'Round-robin sends each request to the next server in turn.',
    'Health checks continuously ping servers; unhealthy ones are pulled from the pool.',
    'When a server dies mid-traffic, the balancer reroutes instantly — clients never notice.',
  ],
  scene: {
    code: [
      'pool = [A, B, C]            # healthy servers',
      'next = 0',
      'on request:',
      '    s = pool[next]',
      '    next = (next + 1) % len(pool)',
      '    forward(request, s)',
      'on healthcheck_fail(s):',
      '    pool.remove(s)          # stop routing to it',
    ],
    initialState: { algorithm: 'round-robin', healthy: 3, requests: 0 },
    nodes: [
      { id: 'client', kind: 'client', label: 'Clients', x: 12, y: 50 },
      { id: 'lb', kind: 'loadBalancer', label: 'Load Balancer', x: 42, y: 50 },
      { id: 's1', kind: 'server', label: 'Server A', x: 82, y: 22, badge: 'healthy' },
      { id: 's2', kind: 'server', label: 'Server B', x: 82, y: 50, badge: 'healthy' },
      { id: 's3', kind: 'server', label: 'Server C', x: 82, y: 78, badge: 'healthy' },
    ],
    edges: [
      { id: 'c-lb', from: 'client', to: 'lb' },
      { id: 'lb-s1', from: 'lb', to: 's1', curve: -0.35 },
      { id: 'lb-s2', from: 'lb', to: 's2' },
      { id: 'lb-s3', from: 'lb', to: 's3', curve: 0.35 },
    ],
    steps: [
      { id: '1', caption: 'A request hits the load balancer — the single public address.', travel: 'c-lb', token: 'request', codeLine: 3, state: { requests: 1 } },
      { id: '2', caption: 'Round-robin forwards it to Server A.', travel: 'lb-s1', token: 'request', codeLine: 4, patches: [{ nodeId: 's1', badge: '1 req', highlight: true }] },
      { id: '3', caption: 'The next request goes to Server B, then C — evenly spread.', travel: 'lb-s2', token: 'request', codeLine: 4, patches: [{ nodeId: 's2', badge: '1 req', highlight: true }], state: { requests: 2 } },
      { id: '4', caption: 'A health check to Server B fails — it has crashed.', travel: 'lb-s2', token: 'miss', codeLine: 7, patches: [{ nodeId: 's2', badge: '✗ down', highlight: true }], state: { healthy: 2 } },
      { id: '5', caption: 'The balancer removes B from the pool. It\'s no longer a target.', codeLine: 8, patches: [{ nodeId: 's2', badge: 'removed' }] },
      { id: '6', caption: 'The request that would\'ve gone to B is rerouted to C — no error reaches the client.', travel: 'lb-s3', token: 'request', codeLine: 6, patches: [{ nodeId: 's3', badge: '2 req', highlight: true }], state: { requests: 3 } },
    ],
  },
}

const caching: Lesson = {
  slug: 'caching',
  title: 'Cache-Aside (Lazy Loading)',
  summary: 'Serve hot data from memory; fall back to the database only on a miss.',
  group: 'building-blocks',
  topic: 'Caching',
  tier: 'free',
  minutes: 7,
  concept: 'Concept',
  tags: [
    { label: 'Latency', value: 'Sub-ms reads' },
    { label: 'Consistency', value: 'Eventual (TTL)' },
    { label: 'Trade-off', value: 'Freshness vs Speed' },
  ],
  notes: [
    'Cache-aside: the app checks the cache first. On a miss it reads the DB, then stores the result.',
    'The next read for the same key is a hit — served from memory in microseconds.',
    'A TTL expires stale entries so the cache doesn\'t serve outdated data forever.',
  ],
  scene: {
    code: [
      'value = cache.get(key)',
      'if value is None:          # MISS',
      '    value = db.query(key)',
      '    cache.set(key, value, ttl=60)',
      'return value               # HIT next time',
    ],
    initialState: { 'cache size': 0, hits: 0, misses: 0, 'hit rate': '0%' },
    nodes: [
      { id: 'client', kind: 'client', label: 'App', x: 12, y: 50 },
      { id: 'cache', kind: 'cache', label: 'Cache', x: 46, y: 26, badge: 'empty' },
      { id: 'db', kind: 'database', label: 'Database', x: 82, y: 68 },
    ],
    edges: [
      { id: 'c-cache', from: 'client', to: 'cache' },
      { id: 'cache-c', from: 'cache', to: 'client', curve: 0.4 },
      { id: 'c-db', from: 'client', to: 'db' },
      { id: 'db-cache', from: 'db', to: 'cache', curve: -0.4 },
    ],
    steps: [
      { id: '1', caption: 'The app looks up the key in the cache first.', travel: 'c-cache', token: 'request', codeLine: 1 },
      { id: '2', caption: 'Cache miss — the key isn\'t there yet.', travel: 'cache-c', token: 'miss', codeLine: 2, patches: [{ nodeId: 'cache', badge: 'MISS', highlight: true }], state: { misses: 1 } },
      { id: '3', caption: 'So the app falls back to the database.', travel: 'c-db', token: 'request', codeLine: 3 },
      { id: '4', caption: 'The DB returns the value, and the app populates the cache with a TTL.', travel: 'db-cache', token: 'write', codeLine: 4, patches: [{ nodeId: 'cache', badge: '1 key', highlight: true }], state: { 'cache size': 1 } },
      { id: '5', caption: 'The same request again — this time it\'s a cache HIT.', travel: 'c-cache', token: 'hit', codeLine: 1, patches: [{ nodeId: 'cache', badge: 'HIT', highlight: true }], state: { hits: 1 } },
      { id: '6', caption: 'Served from memory — no database touch. Hit rate climbs as traffic repeats.', travel: 'cache-c', token: 'hit', codeLine: 5, state: { 'hit rate': '50%' } },
    ],
  },
}

const apiGateway: Lesson = {
  slug: 'api-gateway',
  title: 'API Gateway Routing',
  summary: 'One front door that authenticates, throttles and routes to microservices.',
  group: 'building-blocks',
  topic: 'API Gateway',
  tier: 'free',
  minutes: 6,
  concept: 'Concept',
  tags: [
    { label: 'Pattern', value: 'Façade / Proxy' },
    { label: 'Concerns', value: 'Auth · Rate limit · Routing' },
    { label: 'Coupling', value: 'Loose' },
  ],
  notes: [
    'Clients talk to one endpoint instead of many services.',
    'The gateway handles cross-cutting concerns: auth, rate limiting, logging.',
    'It then routes each request to the right internal service.',
  ],
  scene: {
    code: [
      'on request:',
      '    if not auth.valid(token): return 401',
      '    if rate.exceeded(user):  return 429',
      '    svc = route(request.path)',
      '    return svc.handle(request)',
    ],
    initialState: { authenticated: 'no', route: '—' },
    nodes: [
      { id: 'client', kind: 'client', label: 'Client', x: 10, y: 50 },
      { id: 'gw', kind: 'apiGateway', label: 'API Gateway', x: 40, y: 50 },
      { id: 'users', kind: 'server', label: 'Users Svc', x: 82, y: 22 },
      { id: 'orders', kind: 'server', label: 'Orders Svc', x: 82, y: 50 },
      { id: 'pay', kind: 'server', label: 'Payments', x: 82, y: 78 },
    ],
    edges: [
      { id: 'c-gw', from: 'client', to: 'gw' },
      { id: 'gw-users', from: 'gw', to: 'users', curve: -0.35 },
      { id: 'gw-orders', from: 'gw', to: 'orders' },
      { id: 'gw-pay', from: 'gw', to: 'pay', curve: 0.35 },
    ],
    steps: [
      { id: '1', caption: 'The client sends every request to the single gateway endpoint.', travel: 'c-gw', token: 'request', codeLine: 1 },
      { id: '2', caption: 'The gateway validates the auth token first.', codeLine: 2, patches: [{ nodeId: 'gw', badge: 'auth ✓', highlight: true }], state: { authenticated: 'yes' } },
      { id: '3', caption: 'Then checks the caller hasn\'t exceeded their rate limit.', codeLine: 3, patches: [{ nodeId: 'gw', badge: 'rate ok', highlight: true }] },
      { id: '4', caption: 'A GET /orders is routed to the Orders service.', travel: 'gw-orders', token: 'request', codeLine: 4, patches: [{ nodeId: 'orders', badge: 'handling', highlight: true }], state: { route: '/orders' } },
      { id: '5', caption: 'Different paths fan out to Users or Payments — the client never knows the internal map.', travel: 'gw-users', token: 'request', codeLine: 5, patches: [{ nodeId: 'users', badge: 'handling', highlight: true }] },
    ],
  },
}

const messageQueue: Lesson = {
  slug: 'message-queue',
  title: 'Producer–Consumer Queue',
  summary: 'Decouple producers from consumers so spikes don\'t topple the system.',
  group: 'building-blocks',
  topic: 'Message Queue',
  tier: 'free',
  minutes: 7,
  concept: 'Concept',
  tags: [
    { label: 'Pattern', value: 'Async / Decouple' },
    { label: 'Delivery', value: 'At-least-once' },
    { label: 'Scalability', value: 'Horizontal workers' },
  ],
  notes: [
    'Producers append messages; consumers process them at their own pace.',
    'A traffic spike fills the queue instead of overwhelming the worker.',
    'The backlog drains once load subsides — work is never lost.',
  ],
  scene: {
    code: [
      'producer:  queue.push(job)',
      'consumer:  while true:',
      '    job = queue.pop()      # blocks if empty',
      '    process(job)',
      '    ack(job)',
    ],
    initialState: { depth: 0, processed: 0, 'consumer rate': '1/s' },
    nodes: [
      { id: 'prod', kind: 'server', label: 'Producer', x: 12, y: 50 },
      { id: 'queue', kind: 'queue', label: 'Queue', x: 48, y: 50, badge: '0 jobs' },
      { id: 'cons', kind: 'server', label: 'Consumer', x: 86, y: 50 },
    ],
    edges: [
      { id: 'p-q', from: 'prod', to: 'queue' },
      { id: 'q-c', from: 'queue', to: 'cons' },
    ],
    steps: [
      { id: '1', caption: 'The producer pushes a job onto the queue.', travel: 'p-q', token: 'write', codeLine: 1, patches: [{ nodeId: 'queue', badge: '1 job', highlight: true }], state: { depth: 1 } },
      { id: '2', caption: 'A traffic spike — many jobs arrive at once. The queue absorbs them.', travel: 'p-q', token: 'write', codeLine: 1, patches: [{ nodeId: 'queue', badge: '5 jobs', highlight: true }], state: { depth: 5 } },
      { id: '3', caption: 'The consumer pulls one job and processes it at its own steady rate.', travel: 'q-c', token: 'request', codeLine: 3, patches: [{ nodeId: 'queue', badge: '4 jobs' }], state: { depth: 4, processed: 1 } },
      { id: '4', caption: 'It acks the job; the queue depth drops. The worker is never overwhelmed.', codeLine: 5, patches: [{ nodeId: 'cons', badge: 'ack ✓', highlight: true }], state: { processed: 2 } },
      { id: '5', caption: 'As the spike passes, the backlog drains to empty — no work lost.', travel: 'q-c', token: 'request', codeLine: 3, patches: [{ nodeId: 'queue', badge: '0 jobs', highlight: true }], state: { depth: 0, processed: 5 } },
    ],
  },
}

const rateLimiter: Lesson = {
  slug: 'rate-limiter',
  title: 'Token Bucket Algorithm',
  summary: 'Allow bursts up to a limit, then reject — refilling tokens over time.',
  group: 'building-blocks',
  topic: 'Rate Limiter',
  tier: 'free',
  minutes: 6,
  concept: 'Concept',
  tags: [
    { label: 'Pattern', value: 'Token bucket' },
    { label: 'Latency added', value: '< 1ms' },
    { label: 'Protection', value: 'Burst + sustained' },
  ],
  notes: [
    'A bucket holds up to N tokens; each request spends one.',
    'When the bucket is empty, extra requests are rejected with 429.',
    'Tokens refill at a fixed rate, so steady traffic always gets through.',
  ],
  scene: {
    code: [
      'bucket = 3          # capacity',
      'refill = 1 / sec',
      'on request:',
      '    if bucket > 0:',
      '        bucket -= 1; allow()',
      '    else:',
      '        reject(429)',
    ],
    initialState: { tokens: 3, allowed: 0, rejected: 0 },
    nodes: [
      { id: 'client', kind: 'client', label: 'Client', x: 14, y: 50 },
      { id: 'rl', kind: 'rateLimiter', label: 'Rate Limiter', x: 50, y: 50, badge: '3 tokens' },
      { id: 'svc', kind: 'server', label: 'Service', x: 86, y: 50 },
    ],
    edges: [
      { id: 'c-rl', from: 'client', to: 'rl' },
      { id: 'rl-svc', from: 'rl', to: 'svc' },
      { id: 'rl-c', from: 'rl', to: 'client', curve: 0.5 },
    ],
    steps: [
      { id: '1', caption: 'A request arrives with 3 tokens in the bucket.', travel: 'c-rl', token: 'request', codeLine: 4 },
      { id: '2', caption: 'A token is spent and the request is allowed through.', travel: 'rl-svc', token: 'request', codeLine: 5, patches: [{ nodeId: 'rl', badge: '2 tokens', highlight: true }], state: { tokens: 2, allowed: 1 } },
      { id: '3', caption: 'A rapid burst spends the remaining tokens…', travel: 'rl-svc', token: 'request', codeLine: 5, patches: [{ nodeId: 'rl', badge: '0 tokens', highlight: true }], state: { tokens: 0, allowed: 3 } },
      { id: '4', caption: 'Bucket empty — the next request is rejected with 429.', travel: 'rl-c', token: 'miss', codeLine: 7, patches: [{ nodeId: 'rl', badge: '429 ✗', highlight: true }], state: { rejected: 1 } },
      { id: '5', caption: 'Tokens refill over time, so steady traffic is always let through.', codeLine: 2, patches: [{ nodeId: 'rl', badge: '1 token', highlight: true }], state: { tokens: 1 } },
    ],
  },
}

const replication: Lesson = {
  slug: 'database-replication',
  title: 'Primary–Replica Replication',
  summary: 'One leader takes writes; read replicas scale out reads.',
  group: 'building-blocks',
  topic: 'Database Replication',
  tier: 'free',
  minutes: 7,
  concept: 'Concept',
  tags: [
    { label: 'Availability', value: 'High' },
    { label: 'Consistency', value: 'Eventual' },
    { label: 'Read scale', value: 'Horizontal' },
  ],
  notes: [
    'All writes go to a single leader to keep one source of truth.',
    'The leader streams changes to follower replicas.',
    'Reads are served from followers, multiplying read capacity.',
  ],
  scene: {
    code: [
      'write:  leader.apply(change)',
      '        for f in followers:',
      '            f.stream(change)     # async',
      'read:   pick(followers).query()',
    ],
    initialState: { leader: 'up', 'replicas in sync': 0, 'read capacity': '1x' },
    nodes: [
      { id: 'app', kind: 'client', label: 'App', x: 12, y: 50 },
      { id: 'leader', kind: 'database', label: 'Leader', x: 46, y: 50, badge: 'writes' },
      { id: 'f1', kind: 'database', label: 'Replica 1', x: 84, y: 26, badge: 'reads' },
      { id: 'f2', kind: 'database', label: 'Replica 2', x: 84, y: 74, badge: 'reads' },
    ],
    edges: [
      { id: 'app-leader', from: 'app', to: 'leader' },
      { id: 'leader-f1', from: 'leader', to: 'f1', curve: -0.3 },
      { id: 'leader-f2', from: 'leader', to: 'f2', curve: 0.3 },
      { id: 'f1-app', from: 'f1', to: 'app', curve: 0.5 },
    ],
    steps: [
      { id: '1', caption: 'A write is sent only to the leader — the single source of truth.', travel: 'app-leader', token: 'write', codeLine: 1, patches: [{ nodeId: 'leader', badge: 'applied', highlight: true }] },
      { id: '2', caption: 'The leader streams the change to Replica 1…', travel: 'leader-f1', token: 'write', codeLine: 3, patches: [{ nodeId: 'f1', badge: 'in sync', highlight: true }], state: { 'replicas in sync': 1 } },
      { id: '3', caption: '…and Replica 2. Followers now mirror the leader.', travel: 'leader-f2', token: 'write', codeLine: 3, patches: [{ nodeId: 'f2', badge: 'in sync', highlight: true }], state: { 'replicas in sync': 2, 'read capacity': '2x' } },
      { id: '4', caption: 'Reads are served from a replica, not the leader.', travel: 'f1-app', token: 'response', codeLine: 4, patches: [{ nodeId: 'f1', badge: 'read ✓', highlight: true }] },
      { id: '5', caption: 'Add more replicas to scale reads — the leader stays free for writes.', state: { 'read capacity': '3x+' } },
    ],
  },
}

const lbLeastConnections: Lesson = {
  slug: 'load-balancer-least-connections',
  title: 'Least Connections Algorithm',
  summary: 'Route to the server with the fewest active connections — not just the next in line.',
  group: 'building-blocks',
  topic: 'Load Balancer',
  tier: 'free',
  minutes: 6,
  concept: 'Concept',
  tags: [
    { label: 'Algorithm', value: 'Least connections' },
    { label: 'Best for', value: 'Long-lived connections' },
    { label: 'vs', value: 'Round-robin' },
  ],
  notes: [
    'Round-robin ignores server load — it just takes turns. With mixed request durations, this causes imbalance.',
    'Least Connections tracks active connections per server and always picks the least-loaded one.',
    'Ideal for WebSockets, file uploads, or any workload where requests have variable duration.',
  ],
  scene: {
    code: [
      '# round-robin: blind rotation (ignores load)',
      'server = pool[next % len(pool)]',
      '',
      '# least connections: pick the lightest server',
      'server = min(pool, key=lambda s: s.active_conns)',
    ],
    initialState: { algorithm: 'round-robin', 'next request': '→ Server B' },
    nodes: [
      { id: 'client', kind: 'client', label: 'Clients', x: 12, y: 50 },
      { id: 'lb', kind: 'loadBalancer', label: 'Load Balancer', x: 42, y: 50 },
      { id: 'sa', kind: 'server', label: 'Server A', x: 80, y: 20, badge: '0 conns' },
      { id: 'sb', kind: 'server', label: 'Server B', x: 80, y: 50, badge: '8 conns' },
      { id: 'sc', kind: 'server', label: 'Server C', x: 80, y: 80, badge: '2 conns' },
    ],
    edges: [
      { id: 'c-lb', from: 'client', to: 'lb' },
      { id: 'lb-sa', from: 'lb', to: 'sa', curve: -0.35 },
      { id: 'lb-sb', from: 'lb', to: 'sb' },
      { id: 'lb-sc', from: 'lb', to: 'sc', curve: 0.35 },
    ],
    steps: [
      { id: '1', caption: 'Server B has 8 slow-running connections (large file uploads). A and C are nearly free.', patches: [{ nodeId: 'sb', badge: '8 conns ⚠', highlight: true }], codeLine: 2, state: { algorithm: 'round-robin' } },
      { id: '2', caption: 'Round-robin sends next request to Server B — it\'s just B\'s turn.', travel: 'lb-sb', token: 'request', codeLine: 2, patches: [{ nodeId: 'sb', badge: '9 conns ⚠', highlight: true }], state: { 'next request': '→ Server B (overloaded!)' } },
      { id: '3', caption: 'Bad — B is saturated. Request queues behind 8 others. Latency spikes.', state: { algorithm: 'round-robin', 'next request': 'overloaded' } },
      { id: '4', caption: 'Switch to Least Connections: LB tracks active conn count per server.', codeLine: 5, state: { algorithm: 'least-connections', 'next request': '→ Server A (0 conns)' } },
      { id: '5', caption: 'New request arrives — LB picks Server A (0 connections). Fastest choice.', travel: 'lb-sa', token: 'request', codeLine: 5, patches: [{ nodeId: 'sa', badge: '1 conn', highlight: true }] },
      { id: '6', caption: 'As B\'s uploads finish, its count drops and it naturally gets new traffic again. Self-balancing.', patches: [{ nodeId: 'sb', badge: '3 conns' }, { nodeId: 'sa', badge: '3 conns' }, { nodeId: 'sc', badge: '3 conns' }] },
    ],
  },
}

const cachingWriteThrough: Lesson = {
  slug: 'caching-write-through',
  title: 'Write-Through Cache',
  summary: 'Write to cache and database together — always consistent, never stale.',
  group: 'building-blocks',
  topic: 'Caching',
  tier: 'free',
  minutes: 6,
  concept: 'Concept',
  tags: [
    { label: 'Consistency', value: 'Strong' },
    { label: 'Write cost', value: '2× (cache + DB)' },
    { label: 'Read cost', value: 'Cache-only' },
  ],
  notes: [
    'Write-through: every write goes to cache AND database synchronously before acknowledging the client.',
    'Reads are always cache hits — no cold-start problem after a write.',
    'Trade-off: writes are slower (must wait for both). Best for read-heavy data that\'s written occasionally.',
  ],
  scene: {
    code: [
      '# write-through: update both together',
      'cache.set(key, value)',
      'db.write(key, value)     # synchronous',
      'return ok',
      '',
      '# read: always a cache hit',
      'return cache.get(key)',
    ],
    initialState: { consistency: 'strong', writes: 0, reads: 0 },
    nodes: [
      { id: 'app', kind: 'client', label: 'App', x: 12, y: 50 },
      { id: 'cache', kind: 'cache', label: 'Cache', x: 46, y: 26, badge: 'empty' },
      { id: 'db', kind: 'database', label: 'Database', x: 82, y: 50 },
    ],
    edges: [
      { id: 'a-cache', from: 'app', to: 'cache' },
      { id: 'cache-db', from: 'cache', to: 'db' },
      { id: 'cache-a', from: 'cache', to: 'app', curve: 0.5 },
    ],
    steps: [
      { id: '1', caption: 'App writes a user\'s name. First, it goes into the cache.', travel: 'a-cache', token: 'write', codeLine: 2, patches: [{ nodeId: 'cache', badge: 'writing...', highlight: true }] },
      { id: '2', caption: 'Cache immediately writes through to the database — synchronously.', travel: 'cache-db', token: 'write', codeLine: 3, patches: [{ nodeId: 'db', badge: 'writing', highlight: true }] },
      { id: '3', caption: 'Both are updated. Cache and DB are always in sync. Write acknowledged.', patches: [{ nodeId: 'cache', badge: 'name: Hassan' }, { nodeId: 'db', badge: 'name: Hassan' }], state: { consistency: 'strong', writes: 1 } },
      { id: '4', caption: 'App reads the same key.', travel: 'a-cache', token: 'request', codeLine: 7 },
      { id: '5', caption: 'Cache HIT — the data is there because we wrote it through. Zero DB reads needed.', travel: 'cache-a', token: 'hit', codeLine: 7, patches: [{ nodeId: 'cache', badge: 'HIT ✓', highlight: true }], state: { reads: 1 } },
      { id: '6', caption: 'Trade-off: each write pays 2× cost. But for data that\'s read many times after one write, this wins.', state: { writes: 1, reads: 100, consistency: 'strong' } },
    ],
  },
}

const cachingEvictionLru: Lesson = {
  slug: 'caching-eviction-lru',
  title: 'LRU Cache Eviction',
  summary: 'When cache is full, evict the Least Recently Used entry first.',
  group: 'building-blocks',
  topic: 'Caching',
  tier: 'free',
  minutes: 7,
  concept: 'Concept',
  tags: [
    { label: 'Eviction', value: 'Least Recently Used' },
    { label: 'Complexity', value: 'O(1) get/put' },
    { label: 'Used in', value: 'Redis · Memcached' },
  ],
  notes: [
    'When the cache is full, something must be evicted to make room for new data.',
    'LRU evicts the entry that hasn\'t been accessed for the longest time — the assumption is "if you haven\'t needed it recently, you probably won\'t".',
    'Implemented with a hash map + doubly linked list for O(1) access and eviction.',
  ],
  scene: {
    code: [
      '# cache is full: slots A B C D (A = LRU)',
      'cache.get("E")   # MISS',
      'evict(LRU)       # evict A',
      'cache.set("E")',
      '',
      '# every access moves key to MRU position',
      'cache.get("B")   # B becomes MRU',
    ],
    initialState: { slots: 'A  B  C  D', LRU: 'A', MRU: 'D', hits: 0, misses: 0, evicted: 'none' },
    nodes: [
      { id: 'app', kind: 'client', label: 'App', x: 12, y: 50 },
      { id: 'cache', kind: 'cache', label: 'Cache (full)', x: 50, y: 50, badge: 'A B C D' },
      { id: 'db', kind: 'database', label: 'Database', x: 86, y: 50 },
    ],
    edges: [
      { id: 'a-cache', from: 'app', to: 'cache' },
      { id: 'a-db', from: 'app', to: 'db', curve: 0.4 },
      { id: 'db-cache', from: 'db', to: 'cache', curve: -0.4 },
      { id: 'cache-a', from: 'cache', to: 'app', curve: 0.4 },
    ],
    steps: [
      { id: '1', caption: 'Cache holds A, B, C, D (4 slots full). A is the Least Recently Used.', codeLine: 1, state: { slots: 'A  B  C  D', LRU: 'A', MRU: 'D' } },
      { id: '2', caption: 'App requests key E — not in cache. Cache miss!', travel: 'a-cache', token: 'miss', codeLine: 2, patches: [{ nodeId: 'cache', badge: 'MISS ✗', highlight: true }], state: { misses: 1 } },
      { id: '3', caption: 'Cache is full. LRU policy evicts A — it hasn\'t been touched the longest.', codeLine: 3, patches: [{ nodeId: 'cache', badge: '_ B C D', highlight: true }], state: { evicted: 'A', slots: '_  B  C  D' } },
      { id: '4', caption: 'E is fetched from the database.', travel: 'a-db', token: 'request', codeLine: 4 },
      { id: '5', caption: 'E is stored in A\'s old slot. Cache now holds E, B, C, D.', travel: 'db-cache', token: 'write', codeLine: 4, patches: [{ nodeId: 'cache', badge: 'E B C D', highlight: true }], state: { slots: 'E  B  C  D', LRU: 'B', MRU: 'E' } },
      { id: '6', caption: 'App accesses B — cache hit. B is now the MRU, moves to front of queue.', travel: 'a-cache', token: 'hit', codeLine: 7, patches: [{ nodeId: 'cache', badge: 'HIT: B', highlight: true }], state: { hits: 1, LRU: 'C', MRU: 'B' } },
      { id: '7', caption: 'If A is requested now — cache miss. It was evicted. Must reload from DB.', travel: 'a-cache', token: 'miss', codeLine: 2, state: { misses: 2 } },
    ],
  },
}

const mqFanout: Lesson = {
  slug: 'message-queue-fanout',
  title: 'Fan-out / Pub-Sub Pattern',
  summary: 'One event, many consumers — publish once, every subscriber gets a copy.',
  group: 'building-blocks',
  topic: 'Message Queue',
  tier: 'free',
  minutes: 7,
  concept: 'Concept',
  tags: [
    { label: 'Pattern', value: 'Pub-Sub / Fan-out' },
    { label: 'Coupling', value: 'Loose' },
    { label: 'Delivery', value: 'At-least-once' },
  ],
  notes: [
    'A publisher sends one message to a topic. Every subscribed queue gets a copy.',
    'Services are fully decoupled — the publisher doesn\'t know how many consumers exist.',
    'Used everywhere: photo upload triggers email, thumbnail generation, and analytics independently.',
  ],
  scene: {
    code: [
      'topic.publish("photo-upload", { user_id, photo_id })',
      '',
      '# each subscriber receives its own copy:',
      'email_queue.subscribe(topic)',
      'thumb_queue.subscribe(topic)',
      'analytics_queue.subscribe(topic)',
    ],
    initialState: { 'event type': '—', consumers: 3 },
    nodes: [
      { id: 'pub', kind: 'client', label: 'Publisher', x: 10, y: 50 },
      { id: 'topic', kind: 'queue', label: 'Topic', x: 34, y: 50, badge: 'photo-upload' },
      { id: 'q1', kind: 'queue', label: 'Email Queue', x: 60, y: 20 },
      { id: 'q2', kind: 'queue', label: 'Thumb Queue', x: 60, y: 50 },
      { id: 'q3', kind: 'queue', label: 'Analytics Q', x: 60, y: 80 },
      { id: 'svc1', kind: 'server', label: 'Email Svc', x: 88, y: 20 },
      { id: 'svc2', kind: 'server', label: 'Thumb Svc', x: 88, y: 50 },
      { id: 'svc3', kind: 'server', label: 'Analytics', x: 88, y: 80 },
    ],
    edges: [
      { id: 'pub-topic', from: 'pub', to: 'topic' },
      { id: 'topic-q1', from: 'topic', to: 'q1', curve: -0.2 },
      { id: 'topic-q2', from: 'topic', to: 'q2' },
      { id: 'topic-q3', from: 'topic', to: 'q3', curve: 0.2 },
      { id: 'q1-svc1', from: 'q1', to: 'svc1' },
      { id: 'q2-svc2', from: 'q2', to: 'svc2' },
      { id: 'q3-svc3', from: 'q3', to: 'svc3' },
    ],
    steps: [
      { id: '1', caption: 'User uploads a photo. Publisher emits one event to the topic.', travel: 'pub-topic', token: 'write', codeLine: 1, patches: [{ nodeId: 'topic', badge: '1 msg', highlight: true }], state: { 'event type': 'photo-upload' } },
      { id: '2', caption: 'Topic fans the event out to the Email Queue.', travel: 'topic-q1', token: 'write', codeLine: 4, patches: [{ nodeId: 'q1', badge: '1 msg', highlight: true }] },
      { id: '3', caption: 'Same event goes to the Thumbnail Queue.', travel: 'topic-q2', token: 'write', codeLine: 5, patches: [{ nodeId: 'q2', badge: '1 msg', highlight: true }] },
      { id: '4', caption: 'And the Analytics Queue. Publisher doesn\'t know how many consumers exist.', travel: 'topic-q3', token: 'write', codeLine: 6, patches: [{ nodeId: 'q3', badge: '1 msg', highlight: true }] },
      { id: '5', caption: 'Email Service sends a confirmation email.', travel: 'q1-svc1', token: 'request', patches: [{ nodeId: 'svc1', badge: 'email sent ✓', highlight: true }] },
      { id: '6', caption: 'Thumbnail Service generates a resized image — completely independent.', travel: 'q2-svc2', token: 'request', patches: [{ nodeId: 'svc2', badge: 'thumb done ✓', highlight: true }] },
      { id: '7', caption: 'Analytics records the upload. All 3 run in parallel, at their own pace.', travel: 'q3-svc3', token: 'request', patches: [{ nodeId: 'svc3', badge: 'logged ✓', highlight: true }], state: { 'event type': 'photo-upload', consumers: 3 } },
    ],
  },
}

const rlSlidingWindow: Lesson = {
  slug: 'rate-limiter-sliding-window',
  title: 'Sliding Window Counter',
  summary: 'More precise than token bucket — counts exact requests in the last N seconds.',
  group: 'building-blocks',
  topic: 'Rate Limiter',
  tier: 'free',
  minutes: 6,
  concept: 'Concept',
  tags: [
    { label: 'Algorithm', value: 'Sliding window' },
    { label: 'Precision', value: 'Exact count' },
    { label: 'Problem solved', value: 'Fixed window burst' },
  ],
  notes: [
    'Fixed window flaw: 100 req/min limit but a burst at 0:59 and 1:01 lets through 200 in 2 seconds.',
    'Sliding window counts the exact number of requests in the last 60 seconds, not the current minute.',
    'Slightly more memory (stores per-second buckets) but much more accurate protection.',
  ],
  scene: {
    code: [
      '# FIXED window flaw:',
      'window = current_minute   # resets at :00',
      'if count[window] < 100: allow()',
      '',
      '# SLIDING window fix:',
      'now = time()',
      'count = requests_in_range(now - 60s, now)',
      'if count < 100: allow()',
    ],
    initialState: { algorithm: 'fixed window', 'requests in window': 0, limit: 100 },
    nodes: [
      { id: 'client', kind: 'client', label: 'Client', x: 12, y: 50 },
      { id: 'rl', kind: 'rateLimiter', label: 'Rate Limiter', x: 50, y: 50, badge: '0 / 100' },
      { id: 'svc', kind: 'server', label: 'Service', x: 86, y: 50 },
    ],
    edges: [
      { id: 'c-rl', from: 'client', to: 'rl' },
      { id: 'rl-svc', from: 'rl', to: 'svc' },
      { id: 'rl-c', from: 'rl', to: 'client', curve: 0.5 },
    ],
    steps: [
      { id: '1', caption: 'Fixed window flaw: 50 requests arrive at 0:59 — still in minute 0. All pass.', travel: 'c-rl', token: 'request', codeLine: 3, patches: [{ nodeId: 'rl', badge: '50 / 100', highlight: true }], state: { algorithm: 'fixed window', 'requests in window': 50 } },
      { id: '2', caption: '50 more arrive at 1:01 — new minute, counter reset to 0. All pass too!', travel: 'rl-svc', token: 'request', codeLine: 3, patches: [{ nodeId: 'rl', badge: '50 / 100 ⚠', highlight: true }], state: { 'requests in window': 100 } },
      { id: '3', caption: '100 requests got through in just 2 seconds — twice the intended rate. Fixed windows can be gamed.', patches: [{ nodeId: 'rl', badge: '100 in 2s ⚠', highlight: true }] },
      { id: '4', caption: 'Sliding window: count requests in the last 60 seconds, not the current minute.', codeLine: 7, state: { algorithm: 'sliding window', 'requests in window': 50 }, patches: [{ nodeId: 'rl', badge: '50 / 100', highlight: true }] },
      { id: '5', caption: 'At 1:01, the 50 requests from 0:59 are still inside the 60s window. Count = 100. Reject!', travel: 'rl-c', token: 'miss', codeLine: 8, patches: [{ nodeId: 'rl', badge: '429 ✗ 100/100', highlight: true }], state: { 'requests in window': 100 } },
      { id: '6', caption: 'As old requests age out of the window, new ones are allowed. Precise, smooth protection.', patches: [{ nodeId: 'rl', badge: '60 / 100', highlight: true }], state: { 'requests in window': 60 } },
    ],
  },
}

const replicationLag: Lesson = {
  slug: 'database-replication-lag',
  title: 'Replication Lag & Stale Reads',
  summary: 'Replicas take time to catch up — reading stale data is a real risk.',
  group: 'building-blocks',
  topic: 'Database Replication',
  tier: 'free',
  minutes: 7,
  concept: 'Concept',
  tags: [
    { label: 'Consistency', value: 'Eventual' },
    { label: 'Lag', value: 'Typically < 1s' },
    { label: 'Risk', value: 'Read-after-write' },
  ],
  notes: [
    'Replication is asynchronous by default — the leader commits, then ships the change to replicas.',
    'During the lag window (ms to seconds), reads from a replica return stale data.',
    'Fix: "read-your-writes" consistency — route reads to the leader right after a write.',
  ],
  scene: {
    code: [
      '# write: always to leader',
      'leader.execute("UPDATE bio = \'new bio\'")',
      '# replication: async, ~50ms later',
      'replica.apply(change)',
      '',
      '# fix: read-your-writes',
      'if recently_wrote: read(leader)',
      'else:              read(replica)',
    ],
    initialState: { 'primary bio': 'old bio', 'replica bio': 'old bio', lag: '0ms', 'reader sees': '—' },
    nodes: [
      { id: 'writer', kind: 'client', label: 'Writer App', x: 10, y: 28 },
      { id: 'reader', kind: 'client', label: 'Reader App', x: 10, y: 72 },
      { id: 'primary', kind: 'database', label: 'Primary DB', x: 50, y: 28, badge: 'v5: old bio' },
      { id: 'replica', kind: 'database', label: 'Replica DB', x: 50, y: 72, badge: 'v4: old bio' },
      { id: 'sync', kind: 'queue', label: 'Repl. Queue', x: 80, y: 50, badge: 'async' },
    ],
    edges: [
      { id: 'w-p', from: 'writer', to: 'primary' },
      { id: 'p-sync', from: 'primary', to: 'sync', curve: -0.2 },
      { id: 'sync-r', from: 'sync', to: 'replica', curve: -0.2 },
      { id: 'r-reader', from: 'replica', to: 'reader', curve: 0.3 },
      { id: 'reader-r', from: 'reader', to: 'replica' },
    ],
    steps: [
      { id: '1', caption: 'Writer updates the user\'s bio. Write goes directly to the Primary.', travel: 'w-p', token: 'write', codeLine: 2, patches: [{ nodeId: 'primary', badge: 'v6: new bio ✓', highlight: true }], state: { 'primary bio': 'new bio (v6)' } },
      { id: '2', caption: 'Primary commits instantly and queues the change for replication.', travel: 'p-sync', token: 'write', codeLine: 3, patches: [{ nodeId: 'sync', badge: 'pending', highlight: true }], state: { lag: '~50ms pending' } },
      { id: '3', caption: 'Reader immediately queries the Replica for the bio (e.g., page refresh).', travel: 'reader-r', token: 'request', codeLine: 7 },
      { id: '4', caption: 'Replica hasn\'t applied the change yet. Returns OLD bio. Stale read!', travel: 'r-reader', token: 'miss', codeLine: 7, patches: [{ nodeId: 'replica', badge: 'v5: old bio ⚠', highlight: true }], state: { 'reader sees': 'old bio (stale!)', lag: '50ms' } },
      { id: '5', caption: '50ms later, the replica applies the change. It\'s now consistent.', travel: 'sync-r', token: 'write', codeLine: 4, patches: [{ nodeId: 'replica', badge: 'v6: new bio ✓', highlight: true }], state: { 'replica bio': 'new bio (v6)', lag: '0ms' } },
      { id: '6', caption: 'Fix: right after a write, route reads to the Primary (read-your-writes). Route to replicas otherwise.', codeLine: 7, state: { 'reader sees': 'new bio ✓' } },
    ],
  },
}

export const buildingBlocks: Lesson[] = [
  loadBalancer, lbLeastConnections,
  caching, cachingWriteThrough, cachingEvictionLru,
  apiGateway,
  messageQueue, mqFanout,
  rateLimiter, rlSlidingWindow,
  replication, replicationLag,
]
